### ISSUE TITLE
 Statistics of the datasets

### ISSUE THREAD

**Issue by Book1996** [kuandeng/LightGCN#11]
I downloaded the amazon book dataset of 10-core. But i get different statistics of the datasets: item_num = 128939, user_num = 158650, sample = 4701968. Thus, could you give me the code of preprocessing of amazon book dataset, please. It is really important to me.

**Comment by LouHerGetUp** [comment]
Did you get the code for the data preprocessing? I have the same question regarding this issue. Can you share your answer? This is also very important for me. Thank you so much!
